// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIkxCSaOBhNcNiQY7ApXTjPSA7vbHNf_c',
    appId: '1:208524939231:web:df41fdf7facc18439d7e6a',
    messagingSenderId: '208524939231',
    projectId: 'notebook-project-8b1e8',
    authDomain: 'notebook-project-8b1e8.firebaseapp.com',
    storageBucket: 'notebook-project-8b1e8.firebasestorage.app',
    measurementId: 'G-YQT6C8VLQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGBJiIe5q99oCz2umMjcklyVA7jK3Y4lU',
    appId: '1:208524939231:android:5f3f136cd0feb6b49d7e6a',
    messagingSenderId: '208524939231',
    projectId: 'notebook-project-8b1e8',
    storageBucket: 'notebook-project-8b1e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABRqEULbQ_RgG6Qb28KSSw9rtGZ5td2Ds',
    appId: '1:208524939231:ios:834d58d87d294d119d7e6a',
    messagingSenderId: '208524939231',
    projectId: 'notebook-project-8b1e8',
    storageBucket: 'notebook-project-8b1e8.firebasestorage.app',
    iosBundleId: 'ma.notebook.notebookProjectf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABRqEULbQ_RgG6Qb28KSSw9rtGZ5td2Ds',
    appId: '1:208524939231:ios:834d58d87d294d119d7e6a',
    messagingSenderId: '208524939231',
    projectId: 'notebook-project-8b1e8',
    storageBucket: 'notebook-project-8b1e8.firebasestorage.app',
    iosBundleId: 'ma.notebook.notebookProjectf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIkxCSaOBhNcNiQY7ApXTjPSA7vbHNf_c',
    appId: '1:208524939231:web:6a5688fd810f36869d7e6a',
    messagingSenderId: '208524939231',
    projectId: 'notebook-project-8b1e8',
    authDomain: 'notebook-project-8b1e8.firebaseapp.com',
    storageBucket: 'notebook-project-8b1e8.firebasestorage.app',
    measurementId: 'G-97CKXJ6YDN',
  );
}
